### ISSUE TITLE
Looks like changing of color is not working

### ISSUE THREAD

**Issue by chyrta** [vonovak/react-native-bottom-toolbar#3]
Maybe I'm doing something in the wrong direction while implementing this component into my project, but I can't change the color of the toolbar.

**Comment by vonovak** [comment]
you mean the backgroundColor? yes, that one is not implemented. I might get to do it sooner or later, if you can make a PR, I'd merge it.

**Comment by vonovak** [comment]
@chyrta actually, you should be able to change it using the `wrapperStyle` prop
