### ISSUE TITLE
Upgrade react-native-vector-icons to latest (4.4.3)

### ISSUE THREAD

**Issue by elliottkopp** [vonovak/react-native-bottom-toolbar#5]
This library uses version 3 of react-native-vector-icons.  V3 of the icon dependency uses React.propTypes instead of the new prop-types node module.  React.propTypes was deprecated in version 16 of React.

This means that anyone using react-native-bottom-toolbar cannot upgrade to version 16 of React.  Please update the dependency of react-native-vector-icons to 4.4.3.

I have created pull request https://github.com/vonovak/react-native-bottom-toolbar/pull/6 for this.  I have tested this locally in my app and it works.  

Thanks!

**Comment by vonovak** [comment]
released as 3.0.1
