### ISSUE TITLE
Button Position keeps changing when rendered on Map

### ISSUE THREAD

**Issue by rashrao76** [vonovak/react-native-bottom-toolbar#7]
hi
i tried to use react-native-bottom-toolbar inside the MapView (provider : google).
The position of the buttons keeps moving to different parts of the screen.
need help to fix this.
below is the code i have tried
<MapView style={styles.map}
       region={{
         latitude:20.5937, longitude:78.9629, latitudeDelta:35, longitudeDelta:35
       }}
       provider="google" mapType="satellite"
      >
    <View style={styles.container}>
    <BottomToolbar buttonStyle = {styles.button} onPress={this.onToolbarPress}>
           <BottomToolbar.Action   title="Voice">
             <BottomToolbar.NestedAction title="Analyze" onPress={(index: number, actionPressed: Object) => {Alert.alert('Analyze');}}/>
             <BottomToolbar.NestedAction title="Delete" style="destructive" />
     </BottomToolbar>
</View>
    </MapView>

**Comment by vonovak** [comment]
hi, sorry you're having a problem. Unfortunately, this is not actionable without a runnable reproduction. Please open a new issue with a repro if you're still having this problem.
